### ISSUE TITLE
generator.py kwargs.pop fails.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1367]
I'm using Python 3. Any idea why keep running into this?

Traceback (most recent call last):
  File "../Vulkan-LoaderAndValidationLayers/scripts/lvl_genvk.py", line 19, in <module>
    from reg import *
  File "/home/travis/build/KhronosGroup/Vulkan-LoaderAndValidationLayers/scripts/reg.py", line 160, in <module>
    from generator import write, GeneratorOptions, OutputGenerator
  File "/home/travis/build/KhronosGroup/Vulkan-LoaderAndValidationLayers/scripts/generator.py", line 20
    file = kwargs.pop(u'file',sys.stdout)

**Comment by mre4ce** [comment]
My bad I guess. This works with Travis dist: trusty but not Travis dist: precise
