### ISSUE TITLE
Vulkan crashes if XDG_DATA_DIRS ends in a :

### ISSUE THREAD

**Issue by n3rdopolis** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1474]
It seems that if I unset XDG_DATA_DIRS for instance, or run
```
export XDG_DATA_DIRS=/opt/share:/usr/share:$XDG_DATA_DIRS
```
when XDG_DATA_DIRS is not unset, this obviously gets it to end in a : 
Trying to run vulkaninfo with XDG_DATA_DIRS ending in a : results in a crash

Removing the :, allows it to run

```
Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/i386/i686/multiarch/memcpy-sse2-unaligned.S:578
578     ../sysdeps/i386/i686/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
#0  __memcpy_sse2_unaligned () at ../sysdeps/i386/i686/multiarch/memcpy-sse2-unaligned.S:578
No locals.
#1  0xf7f1b1ab in loader_get_manifest_files (inst=inst@entry=0x0, env_override=<optimized out>, 
    env_override@entry=0xf7f4b3ca "\376\377", <incomplete sequence \304>, is_layer=is_layer@entry=true, 
    relative_location=0xf7f3a441 "/vulkan/explicit_layer.d", out_files=0xffffcdc0, 
    warn_if_not_present=<optimized out>, location=0xf7f3fdf6 "", source_override=0x0)
    at /srcbuild/vulkan/loader/loader.c:2712
        s = <optimized out>
        x = 0xffffdbaf ":/usr/lib/girepository-1.0/"
        loc_size = <optimized out>
        xdgconfdirs = <optimized out>
        xdgdatadirs = <optimized out>
        rel_size = <optimized out>
        loc_write = 0x70657292 <error: Cannot access memory at address 0x70657292>
        loc_read = <optimized out>
        override = <optimized out>
        override_getenv = <optimized out>
        loc = <optimized out>
        file = <optimized out>
        next_file = <optimized out>
        name = <optimized out>
        alloced_count = 64
        full_path = "ory-1.0/", '\000' <repeats 389 times>...
        sysdir = 0x0
        list_is_dirs = <optimized out>
        dent = <optimized out>
        res = VK_SUCCESS
#2  0xf7f1fd1c in loader_layer_scan (inst=0x0, instance_layers=0xffffce14)
    at /srcbuild/vulkan/loader/loader.c:3207
        file_str = <optimized out>
        manifest_files = {{count = 0, filename_list = 0x0}, {count = 0, filename_list = 0x0}}
        json = 0x0
        implicit = <optimized out>
        lockedMutex = false
#3  0xf7f25bba in vkEnumerateInstanceLayerProperties (pPropertyCount=0xffffcf70, pProperties=0x0)
    at /srcbuild/vulkan/loader/trampoline.c:219
        instance_layer_list = {capacity = 0, count = 0, list = 0x0}
        copy_size = <optimized out>
#4  0x08048eb6 in AppGetInstanceExtensions (inst=0xffffcef0) at /srcbuild/vulkan/demos/vulkaninfo.c:549
        err = <optimized out>
        count = 0
        global_layer_properties = 0x0
        global_layers = 0x0
#5  AppCreateInstance (inst=0xffffcef0) at /srcbuild/vulkan/demos/vulkaninfo.c:590
        i = <optimized out>
        ext_count = <optimized out>
        app_info = {sType = VK_STRUCTURE_TYPE_APPLICATION_INFO, pNext = 0x1, pApplicationName = 0xf7ffd918 "", 
          applicationVersion = 4158446523, pEngineName = 0xffffcf6e "\004\b", engineVersion = 0, 
          apiVersion = 4160629056}
        inst_info = {sType = VK_STRUCTURE_TYPE_APPLICATION_INFO, pNext = 0xffffd014, flags = 4159635456, 
          pApplicationInfo = 0x16, enabledLayerCount = 4294967295, ppEnabledLayerNames = 0xf7ef0000, 
          enabledExtensionCount = 4157906456, ppEnabledExtensionNames = 0xf7fd4860}
        dbg_info = {sType = VK_STRUCTURE_TYPE_APPLICATION_INFO, pNext = 0x0, flags = 0, 
          pfnCallback = 0xf7ffd000, pUserData = 0xf7ffdc08}
        err = <optimized out>
        ext_names = {0xffffcef0 "", 0xffffcf80 "\377\377\377\377", 
          0x8ee <error: Cannot access memory at address 0x8ee>, 0x0}
#6  main (argc=1, argv=0xffffd074) at /srcbuild/vulkan/demos/vulkaninfo.c:1454
        gpus = <optimized out>
        objs = <optimized out>
        gpu_count = 129100401
        err = <optimized out>
        inst = {instance = 0x0, global_layer_count = 0, global_layers = 0x0, 
          global_extension_count = 4294954892, global_extensions = 0xf7fe1e99 <do_lookup_x+9>, 
          vkGetPhysicalDeviceSurfaceSupportKHR = 0x0, vkGetPhysicalDeviceSurfaceCapabilitiesKHR = 0xf7ffdad0, 
          vkGetPhysicalDeviceSurfaceFormatsKHR = 0xffffcf88, 
          vkGetPhysicalDeviceSurfacePresentModesKHR = 0xffffcfd0, surface = 577731568567462427, 
          width = -12408, height = -134227340, xcb_connection = 0x6, xcb_screen = 0xf7d37428, xcb_window = 1}
        format_count = <optimized out>
        present_mode_count = <optimized out>

```

**Comment by MarkY-LunarG** [comment]
Thanks Karl for fixing this.

**Comment by MarkY-LunarG** [comment]
And thanks @n3rdopolis for catching this.
